/*******************************************************************************

                   SDR_func.c module of the program ARM_Radio
						                          
						                          Copyright 2015 by Alberto I2PHD, June 2015
						                                      
    This file is part of ARM_Radio.

    ARM_Radio is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    ARM_Radio is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with ARM_Radio.  It is contained in the file Copying.txt in the
    same ZIP file where this file was extracted from.				                                      
						                                      
*******************************************************************************/

#include "main.h"
#include <arm_const_structs.h>
#include "fftmask.h"
#include "Presets.h"

//#include "Presets.h"

//-----------------------------------------------------------------------------
uint32_t bouncing(void)
{	
	int delta;
	static int last_time = 0;
	
  delta = os_time - last_time;
	last_time = os_time; 
// if less than 100 time units have elapsed from the previous
// invokation, then bouncing...  
	return delta < 100;  
}
//-----------------------------------------------------------------------------



// Load from the Presets table
void Load_Presets(void)
{
  int k;

  for(k=0; k<MAXPRESETS; k++)
  {
    strcpy(psets[k].name, pNames[k]);
    psets[k].freq = pFreqs[k];
    psets[k].mode = pModes[k];
    psets[k].bw   = pBws[k];    
  }    
}
//-----------------------------------------------------------------------------
// Tune to the chosen preset
void Tune_Preset(u8 Idx)
{
  int kHz, Hz;
  
  LOfreq = psets[Idx].freq; 
	SetMode( psets[Idx].mode);
  SetBW( psets[Idx].bw);
	strcpy(msg, psets[Idx].name);

  kHz = LOfreq / 1000.f;  Hz = LOfreq - kHz*1000;		 

	 DisplayFrequency();

}



//-----------------------------------------------------------------------------
// Manage the interrupt generated by the pressing of the User button
void EXTI0_IRQHandler()                                                          
{
  static u8 Idx = 1;
  if(EXTI_GetITStatus(EXTI_Line0) != RESET)
  {		
// User button pressed, cycle through all the presets
    Idx++; if(Idx >= MAXPRESETS) Idx = 1;
    Tune_Preset(Idx);
  }	

  /* Clear the EXTI line 0 pending bit */
//    EXTI_ClearITPendingBit(EXTI_Line0);
	EXTI->PR = EXTI_Line0; // clear the 'interrupt pending' status

}	



//-----------------------------------------------------------------------------
// Load the FFT mask according to the mode and the bandwidth chosen,
// and change the color of the buttons to indicate the active bandwidth
void SetBW(/*WM_HWIN ptr,*/ Bwidth newbw)
{
	switch(currentmode)
	{
	  case AM :
      bw[AM] = newbw;
      AMindex = (newbw == Narrow) ? 0 : 1;
      SDR_2R_toC_f32((float *)FFTmaskAM_R[AMindex], 
				             (float *)FFTmaskAM_I[AMindex], FFTmask, FFTLEN);	
//      ChangeColor(ptr, hNARROW, AMindex == 0 ? GUI_RED   : GUI_BLACK);		
//      ChangeColor(ptr, hWIDE,   AMindex == 0 ? GUI_BLACK : GUI_RED);		
		  break;                
		
    case LSB :
      bw[LSB] = newbw;
      LSBindex = (newbw == Narrow) ? 0 : 1;
  		SDR_2R_toC_f32((float *)FFTmaskSSB_R[LSBindex], 
				             (float *)FFTmaskSSB_I[LSBindex], FFTmask, FFTLEN);	
//      ChangeColor(ptr, hNARROW, LSBindex == 0 ? GUI_RED   : GUI_BLACK);		
//      ChangeColor(ptr, hWIDE,   LSBindex == 0 ? GUI_BLACK : GUI_RED);		
      break; 

    case USB :
      bw[USB] = newbw;
      USBindex = (newbw == Narrow) ? 0 : 1;
  		SDR_2R_toC_f32((float *)FFTmaskSSB_R[USBindex], 
				             (float *)FFTmaskSSB_I[USBindex], FFTmask, FFTLEN);	
//      ChangeColor(ptr, hNARROW, USBindex == 0 ? GUI_RED   : GUI_BLACK);		
//      ChangeColor(ptr, hWIDE,   USBindex == 0 ? GUI_BLACK : GUI_RED);		
      break; 

    case CW  : 			
      bw[CW] = newbw;
      CWindex = (newbw == Narrow) ? 0 : 1;
  		SDR_2R_toC_f32((float *)FFTmaskCW_R[CWindex], 
				             (float *)FFTmaskCW_I[CWindex], FFTmask, FFTLEN);	
//      ChangeColor(ptr, hNARROW, CWindex == 0 ? GUI_RED   : GUI_BLACK);		
//      ChangeColor(ptr, hWIDE,   CWindex == 0 ? GUI_BLACK : GUI_RED);		
      break; 

    default :
      break;		
  }    
}	
//-----------------------------------------------------------------------------
// Change the AGC constants according to the mode and the AGC chosen,
// and change the color of the buttons to indicate the active AGC speed
void SetAGC(/*WM_HWIN ptr,*/ Agctype newAGC)
{
	switch(currentmode)
	{
	  case AM :       agc[AM] = newAGC;
      Decay[AM]   = AGC_decay[newAGC];
      Hcount[AM]  = Hangcount[newAGC]; break;
    
    case LSB :      agc[LSB] = newAGC;
      Decay[LSB]  = AGC_decay[newAGC];
      Hcount[LSB] = Hangcount[newAGC]; break;
    
    case USB :      agc[USB] = newAGC;
      Decay[USB]  = AGC_decay[newAGC];
      Hcount[USB] = Hangcount[newAGC]; break;
    
    case CW :       agc[CW] = newAGC;
      Decay[CW]   = AGC_decay[newAGC];
      Hcount[CW]  = Hangcount[newAGC]; break;
  }    
//  ChangeColor(ptr, hFAST, (newAGC == Fast) ? GUI_RED   : GUI_BLACK);		
//  ChangeColor(ptr, hSLOW, (newAGC == Slow) ? GUI_RED   : GUI_BLACK);		
}	
//-----------------------------------------------------------------------------
// Set the new demodulation mode chosen by the user, and change the color
// of the buttons to indicate the active mode

void SetMode(/*WM_HWIN ptr,*/ Mode newmode)
{
	currentmode = newmode;	

	switch(currentmode)
	{
	  case AM :
      SetBW(/*ptr,*/ bw[AM]); SetAGC(/*ptr,*/ agc[AM]);
//      ChangeColor(ptr, hAM,  GUI_RED);		
//      ChangeColor(ptr, hLSB, GUI_BLACK);		
//      ChangeColor(ptr, hUSB, GUI_BLACK);		
//      ChangeColor(ptr, hCW,  GUI_BLACK);		
		  break;                
		
    case LSB :
      SetBW(/*ptr,*/ bw[LSB]);  SetAGC(/*ptr,*/ agc[LSB]);
//      ChangeColor(ptr, hAM,  GUI_BLACK);		
//      ChangeColor(ptr, hLSB, GUI_RED);		
//      ChangeColor(ptr, hUSB, GUI_BLACK);		
//      ChangeColor(ptr, hCW,  GUI_BLACK);		
      break; 

    case USB :
      SetBW(/*ptr,*/ bw[USB]);  SetAGC(/*ptr,*/ agc[USB]);
 //     ChangeColor(ptr, hAM,  GUI_BLACK);		
 //     ChangeColor(ptr, hLSB, GUI_BLACK);		
 //     ChangeColor(ptr, hUSB, GUI_RED);		
 //     ChangeColor(ptr, hCW,  GUI_BLACK);		
      break; 

    case CW  : 			
      SetBW(/*ptr,*/ bw[CW]);  SetAGC(/*ptr,*/ agc[CW]);
 //     ChangeColor(ptr, hAM,  GUI_BLACK);		
 //     ChangeColor(ptr, hLSB, GUI_BLACK);		
 //     ChangeColor(ptr, hUSB, GUI_BLACK);		
 //     ChangeColor(ptr, hCW,  GUI_RED);		
      break; 

    default :
      break;			
	}
}	
//-----------------------------------------------------------------------------
// Change the color of the button selected by the parameter "handle"

void ChangeColor(WM_HWIN ptr, int handle, int color)
{	
 // WM_HWIN hItem;
	
//	hItem = WM_GetDialogItem(ptr, handle);
 // BUTTON_SetTextColor(hItem, BUTTON_CI_PRESSED, color); 						 
 // BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED, color); 						 
}	

//-----------------------------------------------------------------------------
// Set the frequency step according to the radio button pressed by the user
void SetFstep(int idx)
{
  Fstep = pow(10, 5 - idx);	
}	
//-----------------------------------------------------------------------------
// Increase the frequency by the value of the current step
void FplusClicked()
{	
	LOfreq += Fstep;
  LOfreq  = min(LOfreq, 900000.f);
  psets[0].freq = LOfreq; psets[0].mode = currentmode; 
  psets[0].bw = bw[currentmode]; 
  Tune_Preset(0);  // preset 0 means "User tuning"
}	
//-----------------------------------------------------------------------------
// Decrease the frequency by the value of the current step
void FminusClicked()
{	
	LOfreq -= Fstep;
  LOfreq  = max(LOfreq, 8000.f);
  psets[0].freq = LOfreq; psets[0].mode = currentmode; 
  psets[0].bw = bw[currentmode]; 
  Tune_Preset(0);  // preset 0 means "User tuning"
}



//-----------------------------------------------------------------------------
// Toggle the ON/OFF status of the two on-board Leds
void LED_switch()
{	
  static uint32_t timer_cnt = 0;
	
  //if (++timer_cnt & 1) {LED_On(1); LED_Off(0);} 
	//else                 {LED_On(0); LED_Off(1);}	
}
//-----------------------------------------------------------------------------
// Handle the SysTick interrupt 
void SysTick_Handler()
{
//	uwTick = OS_TimeMS = ++os_time;
	
	if((os_time % 400) == 0) // toggle the green/red Leds every 400 time units
    LED_switch();
}	
//-----------------------------------------------------------------------------
// Hopefully we should never land here.....
void Error_Handler(void)
{
  while(1)
  {
	  if((os_time % 50) == 0)  // blink fast the two leds in case of errors
      LED_switch();
  }
}
//-----------------------------------------------------------------------------
// This is the handler of the software interrupt generated by the highest
// priority task that handles the interrupts generated by DMA2 Stream 0,
// when an ADC buffer is filled
void EXTI1_IRQHandler()   
{
  short  *p;
  static int32_t ToglimiCounter;

	
//#define AG_TEST_AUDIO

#ifdef AG_TEST_AUDIO
 int16_t i;
#endif

//  EXTI_ClearITPendingBit(EXTI_Line1);
  EXTI->PR = EXTI_Line1;	
//	NVIC_ClearPendingIRQ(EXTI1_IRQn);

ToglimiCounter++;

PF8_HI;  // set bit 8 of GPIOF high, to be observed with an oscilloscope


// copy into work buffers the data received by CIC decimator
  SDR_memcpy_f32(Rbase, Rbasedata, BSIZE*4);
  SDR_memcpy_f32(Ibase, Ibasedata, BSIZE*4);




// inverse sync filtering and decimation by 4	
	arm_fir_decimate_f32(&SfirR, Rbase, Rdata, BSIZE*4);
	arm_fir_decimate_f32(&SfirI, Ibase, Idata, BSIZE*4);

// filter now with fast convolution
//---------------------------------
// shift the FFT buffer to the left
  SDR_memcpy_f32(fCbase, fCbase + FFTLEN, FFTLEN);




// insert at the right edge the latest data
  SDR_2R_toC_f32(Rdata, Idata, fCbase + FFTLEN, BSIZE); 



// copy into the (in place...) FFT buffer
  SDR_memcpy_f32(FFTbuf, fCbase, FFTLEN*2);






// compute the direct FFT		
  arm_cfft_f32(&arm_cfft_sR_f32_len1024, FFTbuf, DIRECTFFT, NOREVERSE);

// if LSB, copy the LSB in the lower half (USB)
  if(currentmode == LSB) SDR_mirror_LSB(FFTbuf, FFTLEN);  
// mult. by the fast convolution mask
  arm_cmplx_mult_cmplx_f32(FFTbuf, FFTmask, FFTbuf2, FFTLEN);

// compute now the inverse FFT	
  arm_cfft_f32(&arm_cfft_sR_f32_len1024, FFTbuf2, INVERSEFFT, NOREVERSE);
// then do the overlap-discard
  SDR_memcpy_f32(tmpSamp, FFTbuf2 + 2*FFTLEN - 2*BSIZE, 2*BSIZE);   


// we have now the bandpass filtered I/Q, demodulate the signal 
  switch(currentmode)
	{	
		case AM :
      SDR_demodAM_AGC(tmpSamp, fAudio);  break;
		
		case LSB :
		case USB :
		  SDR_demodSSB_CW_AGC(tmpSamp, fAudio); break;

		case  CW :	
		  SDR_demodSSB_CW_AGC(tmpSamp, fAudio);
      if(bw[CW] == Narrow) SDR_CWPeak(fAudio, BSIZE); break;
		
		default:  
		  break;
	}



#ifdef AG_TEST_AUDIO

  // Il DAC ha sample 27901.786 Hz regolato dal timer 6 (TIM_TimeBaseInit)
  // L'handler dell'interrupt soft è a 27901.786 / 512 = 54.496 Hz
  // Onda quadra periodo 64 campioni = 436 Hz. (32 On 32 Off)
  for (i=0; i<BSIZE; i++)
  {
	  if (i % 64 > 31)
		  fAudio[i] = 0.1; //Volume
	  else
		  fAudio[i] = -0.1;
  }

#endif



// send the demodulated audio to the DMA buffer just emptied
	if(DMA_GetCurrentMemoryTarget(DMA1_Stream6) == 0) p=AudioOut1;
	else                                              p=AudioOut0;
// and reconvert from floating point to short words
  SDR_float_to_DAC_audio(fAudio, p, BSIZE);



PF8_LO;   // set bit 8 of GPIOF low, to be observed with an oscilloscope
}





//-----------------------------------------------------------------------------  
// This the handler of the highest priority task interrupts, those generated
// by DMA2 Stream when a new ADC buffer is just filled
void DMA2_Stream0_IRQHandler(void)
{
  static int16_t k, idx = 0;   


	float sum;

	register float *ptDataR, *ptDataI, inER, inOR, inEI, inOI, outR, outI, 
	               tmp1R, tmp1I, tmp2R, tmp2I, tmp3R, tmp3I;
	
	static   float inE1Rold,  inE2Rold,  inE1Iold,   inE2Iold,  inO1Rold, 
	               inO2Rold,  inO1Iold,  inO2Iold,   inO1Rold2, inO1Iold2,   
	               inO2Rold2, inO2Iold2,             inE3Rold,  inE3Iold,
                   inO3Rold,  inO3Iold,  inO3Rold2,  inO3Iold2, inE4Rold,
	               inE4Iold,  inO4Rold2, inO4Iold2,  inO4Rold,  inO4Iold;
	               
  volatile uint16_t *pR;
  
//#define AG_TEST_SIGNAL

#ifdef AG_TEST_SIGNAL
  uint16_t test_data[BSIZE];
#endif
 	NVIC_ClearPendingIRQ(DMA2_Stream0_IRQn);
	DMA_ClearITPendingBit(DMA2_Stream0, DMA_IT_TCIF0 | DMA_IT_HTIF0);

//PF8_HI;  // uncomment this if you want to measure time spent in this routine


//	ToglimiDMAICounter++;



// process the data contained in the just filled buffer
	if(DMA_GetCurrentMemoryTarget(DMA2_Stream0) == 0)  pR = ADC_Data1;
	else                                               pR = ADC_Data0;



#ifdef AG_TEST_SIGNAL
pR=test_data;
	k = BSIZE;

//Simulo onda quadra a  1.785714 / 16 = 111.607 KHz

	 for (k=0; k< BSIZE; k++)
		{
		  if (k % 16 > 7)
			pR[k] = 2048 + 1000;
		  else
			pR[k] = 2048 - 1000;
		}
#endif


// compute the new NCO buffer, with the CWpitch offset if receiving CW  
 if(currentmode == CW)
	  SDR_ComputeLO(LOfreq-cwpitch);  // prepare next LO buffer
  else
	  SDR_ComputeLO(LOfreq);          // prepare next LO buffer

// compute the smoothed average value of the buffer, to be used as offset
// in the short words to floating point conversion routine  
	sum = 0; k = BSIZE;
  while(k)
	{ 	
		sum += pR[k-1];
		sum += pR[k-2];
		sum += pR[k-3];
		sum += pR[k-4];
		k-=4;
	}	

	TestSampledValue=pR[BSIZE/2];

	mean = sum/(float)BSIZE;



// downconvert to zero IF, by multiplication by the exp(-jwt) signal
// generated by the NCO, and at the same time convert to floating point  
SDR_downconvert_f32((uint16_t *)pR, meanavg, ADC_Rdata, ADC_Idata);
	
	ptDataR = ADC_Rdata;  ptDataI = ADC_Idata;



//-------------------------------------------------------------------------
// Now we decimate by 16 the input samples, using the CIC polyphase decomposition
// technique, which has the advantage of eliminating the recursive
// component, allowing the use of floating point, rather fast on a Cortex M4F
//
// A dividing by 16, order 4, CIC is used. Then a 4096-entry buffer is filled, and
// passed to the baseband interrupt routine, where it is additionally filtered with a
// sync-compensating FIR, which also adds further stop band rejection and a decimation by 4
//-------------------------------------------------------------------------

  k=BSIZE/2;  // BSIZE/2 to process BSIZE entries, two at a time  
  while(k--)
	{	 
// CIC, R=16, M=4, computed in four div_by_2 sections, using the polyphase decomposition
// H(z) = (1 + z^-1)(1 + z^-1)(1 + z^-1)(1 + z^-1) each section, which can be decomposed as follows :
// H(z) = 1 + 4z^-1 + 6z^-2 + 4z^-3 + z^-4 
//        which being separated in even and odd samples in advance becomes
// (1 + 6z^-1 + z^-2) for odd samples and (4 + 4z^-1) for even samples, which, when summed, give :
// odd + 6odd_old + odd_old2 + 4even + 4even_old =	odd + 6odd_old + odd_old2 + 4(even + even_old)		

		inER=*ptDataR++; inOR=*ptDataR++;          inEI=*ptDataI++; inOI=*ptDataI++;  
    outR=(inOR+6.f*inO1Rold+inO1Rold2+4.f*(inER+inE1Rold)); outI=(inOI+6.f*inO1Iold+inO1Iold2+4.f*(inEI+inE1Iold));

		inE1Rold = inER;                           inE1Iold = inEI;
		inO1Rold2 = inO1Rold; inO1Rold = inOR;     inO1Iold2 = inO1Iold; inO1Iold = inOI;

		if((k & 0x1))  // skip the if-block for k multiple of 2 (in base zero), 
			             // else save the even element just produced and cycle the while loop... 
		{	 
      tmp1R = outR; tmp1I = outI;  // save the even element produced
		  continue; 
		}	
		
// at this point we have two elem. (tmp1R[even] and outR[odd] and also the I counterparts)
// produced using 4 input samples, totalling a decimation by 2		
// now compute the couple of elements for the next step

    inER=tmp1R;  inOR=outR;                    inEI=tmp1I;  inOI=outI;
    outR=(inOR+6.f*inO2Rold+inO2Rold2+4.f*(inER+inE2Rold)); outI=(inOI+6.f*inO2Iold+inO2Iold2+4.f*(inEI+inE2Iold));

		inE2Rold = inER;                           inE2Iold = inEI;  
		inO2Rold2 = inO2Rold; inO2Rold = inOR;     inO2Iold2 = inO2Iold; inO2Iold = inOI;
		
		if((k & 0x2)) // skip the if block for k multiple of 4 (in base zero),
			            // else save the even element just produced and cycle the while loop... 
		{	
      tmp2R = outR; tmp2I = outI;  // save the even element produced
		  continue; 
		}	
		
// now we have the input samples decimated by 4, even element in tmp2R, tmp2I,
// and the odd element in outR, outI		
// now compute the couple of elements for the next step
		
    inER=tmp2R;  inOR=outR;                    inEI=tmp2I;  inOI=outI;
    outR=(inOR+6.f*inO3Rold+inO3Rold2+4.f*(inER+inE3Rold)); outI=(inOI+6.f*inO3Iold+inO3Iold2+4.f*(inEI+inE3Iold));

		inE3Rold  = inER;                          inE3Iold  = inEI;  
		inO3Rold2 = inO3Rold; inO3Rold = inOR;     inO3Iold2 = inO3Iold; inO3Iold = inOI;

		if((k & 0x4)) // skip the if block for k multiple of 8 (in base zero),
			            // else save the even element just produced and cycle the while loop... 
		{	
      tmp3R = outR; tmp3I = outI;  // save the even element produced
		  continue; 
		}	

// at this point we have two elem. (tmp3R[even] and outR[odd] and also the I counterparts)
// produced with 4 of the previous elem, i.e. with 16 input samples, totalling 
// a decimation by 8. Now compute the couple of elements for the next step

    inER=tmp3R;  inOR=outR;                    inEI=tmp3I;  inOI=outI;
    outR=(inOR+6.f*inO4Rold+inO4Rold2+4.f*(inER+inE4Rold)); outI=(inOI+6.f*inO4Iold+inO4Iold2+4.f*(inEI+inE4Iold));

		inE4Rold = inER;                           inE4Iold = inEI;  
		inO4Rold2 = inO4Rold; inO4Rold = inOR;     inO4Iold2 = inO4Iold; inO4Iold = inOI;
		
// at this point we have a single element (outR and its counterpart outI), produced 
// with 2 of the previous element, i.e. with 16 input samples, totalling a decimation by 16	
// we downscale it with a factor of 32768, i.e. the gain of the CIC, i.e.	R^M = 16^4 = 65536
// divided by two, to compensate for the 3 dB loss caused by keeping just half of the band    

// create a block of BSIZE*4 entries, which will be then decimated by 4

	  Rbasedata[idx] = outR/32768.f;    Ibasedata[idx++] = outI/32768.f;
		
		if(idx < BSIZE*4) continue;   
		idx = 0;



// generate now an interrupt to signal the base band processing routine that it has a new buffer			 
//	EXTI_GenerateSWInterrupt(EXTI_Line1);
		EXTI->SWIER |= EXTI_Line1;   // expansion of EXTI_GenerateSWInterrupt(EXTI_Line1)
  }	

//PF8_LO;	// uncomment this if you want to measure time spent in this routine
}	
//-----------------------------------------------------------------------------

